name: trialnderror
description: "A new Flutter project."
   #flutter_native_splash:
  #background_image:
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.4
  get: ^4.6.6
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\images\Logo2.png
    - assets\images\gOt.png
    - assets\images\oh.png
    - assets\images\barbie.jpeg
    - assets\images\SR.jpeg


 